repos:
- repo: local
  hooks:
  - id: shellcheck
    name: shellcheck
    entry: shellcheck
    language: system
    types: [shell]
    require_serial: true

  - id: shfmt
    name: shfmt
    entry: shfmt -s -ci -sr -fn -i 2 -w
    language: system
    types: [shell]

  - id: hadolint
    name: hadolint
    entry: hadolint
    language: system
    types: [dockerfile]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint
  rev: v1.29.0
  hooks:
  - id: yamllint
    args: ['-d=relaxed']
    types: [yaml]
