version: "3.9"
services:
  distrobox-debian:
    build:
      context: .
      args:
        - MAKEFLAGS=${MAKEFLAGS:--j4}
        - MARCH=${MARCH:-x86-64-v3}
        - MTUNE=${MTUNE:-generic}
    image: docker.io/pavelxdd/distrobox-debian:sid
    container_name: distrobox-debian
    network_mode: host
    userns_mode: host
    volumes:
      - ${WORKSPACE:-.}:/app
    working_dir: /app
    tmpfs:
      - /tmp:mode=777
      - /root:mode=777
    environment:
      - USER=root
      - HOME=/root
      - WORKSPACE=${WORKSPACE:-.}
      - MAKEFLAGS=${MAKEFLAGS:--j4}
      - MARCH=${MARCH:-x86-64-v3}
      - MTUNE=${MTUNE:-generic}
